name: Build Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.2' # Use the current stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install esbuild globally
        run: npm install -g esbuild

      - name: Run build script
        run: npm run build

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add js/minified-bundle.js
          git commit -m "Update minified bundle" -a || echo "No changes to commit"
          git push
